# Generated by Django 4.0.6 on 2022-08-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survivor.base')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(verbose_name='Idade:')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Gênero:')),
                ('latitude', models.FloatField(max_length=50, verbose_name='Latitude:')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Longitude:')),
            ],
            options={
                'verbose_name': 'Sobrevivente',
                'verbose_name_plural': 'Sobreviventes',
                'ordering': ['id'],
            },
            bases=('survivor.base',),
        ),
    ]
