# Generated by Django 4.0.6 on 2022-08-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='infected',
            field=models.BooleanField(default=False, verbose_name='Infectado'),
        ),
    ]
