# Generated by Django 4.0.6 on 2022-08-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0002_survivor_infected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survivor.base')),
                ('name', models.CharField(max_length=150, verbose_name='Nome:')),
                ('points', models.IntegerField(verbose_name='Pontos:')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['id'],
            },
            bases=('survivor.base',),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='infected',
            field=models.BooleanField(default=False, verbose_name='Sobrevivente Infectado?'),
        ),
    ]
