# Generated by Django 4.0.6 on 2022-08-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0004_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ManyToManyField(to='survivor.item'),
        ),
    ]
