# Generated by Django 4.0.6 on 2022-08-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0006_alter_survivor_latitude_alter_survivor_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='count_reports',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Relatos:'),
        ),
    ]
